#pragma once

typedef enum {
  CMC_ERR_NO,
  CMC_ERR_MEM,
  CMC_ERR_CONNETING,
  CMC_ERR_SOCKET,
  CMC_ERR_CLOSING,
  CMC_ERR_RECV,
  CMC_ERR_INVALID_PACKET_LEN,
  CMC_ERR_ZLIB_INIT,
  CMC_ERR_ZLIB_INFLATE,
  CMC_ERR_SENDER_LYING,
  CMC_ERR_ZLIB_COMPRESS,
  CMC_ERR_SENDING,
  CMC_ERR_KICKED_WHILE_LOGIN,
  CMC_ERR_SERVER_ONLINE_MODE,
  CMC_ERR_UNKOWN_PACKET,
  CMC_ERR_MALLOC_ZERO,
  CMC_ERR_INVALID_ARGUMENTS,
  CMC_ERR_BUFF_UNDERUN,
  CMC_ERR_BUFF_OVERFLOW,
  CMC_ERR_STRING_LENGHT,
  CMC_ERR_INVALID_STRING,
  CMC_ERR_INVALID_LENGHT,
  CMC_ERR_INVALID_NBT_TAG_TYPE,
  CMC_ERR_NOT_IMPLEMENTED_YET,
  CMC_ERR_ASSERT,
  CMC_ERR_UNSUPPORTED_PROTOCOL_VERSION,
  CMC_ERR_UNEXPECTED_PACKET,
  CMC_ERR_REALLOC_ZERO,
  CMC_ERR_NEGATIVE_STRING_LENGHT
} cmc_err;

typedef struct {
  cmc_err err;
  const char *file;
  int line;
} cmc_err_extra;

const char *cmc_err_as_str(cmc_err err);
