#include "err.h"

const char *err_id2str(enum cmc_err_type err) {
#define ERRID2STR_HELPER(ERR)                                                  \
  case ERR:                                                                    \
    return #ERR;
  switch (err) {
    ERRID2STR_HELPER(ERR_NO);
    ERRID2STR_HELPER(ERR_MEM);
    ERRID2STR_HELPER(ERR_CONNETING);
    ERRID2STR_HELPER(ERR_SOCKET);
    ERRID2STR_HELPER(ERR_CLOSING);
    ERRID2STR_HELPER(ERR_RECV);
    ERRID2STR_HELPER(ERR_INVALID_PACKET_LEN);
    ERRID2STR_HELPER(ERR_ZLIB_INIT);
    ERRID2STR_HELPER(ERR_ZLIB_INFLATE);
    ERRID2STR_HELPER(ERR_SENDER_LYING);
    ERRID2STR_HELPER(ERR_ZLIB_COMPRESS);
    ERRID2STR_HELPER(ERR_SENDING);
    ERRID2STR_HELPER(ERR_KICKED_WHILE_LOGIN);
    ERRID2STR_HELPER(ERR_SERVER_ONLINE_MODE);
    ERRID2STR_HELPER(ERR_INVALID_PACKET_ID_WHILE_LOGGING_IN);
    ERRID2STR_HELPER(ERR_MALLOC_ZERO);
    ERRID2STR_HELPER(ERR_INVALID_ARGUMENTS);
    ERRID2STR_HELPER(ERR_BUFFER_UNDERUN);
    ERRID2STR_HELPER(ERR_BUFFER_OVERFLOW);
    ERRID2STR_HELPER(ERR_STRING_LENGHT);
    ERRID2STR_HELPER(ERR_INVALID_STRING);
    ERRID2STR_HELPER(ERR_INVALID_LENGHT);
    ERRID2STR_HELPER(ERR_INVALID_NBT_TAG_TYPE);
    ERRID2STR_HELPER(ERR_NOT_IMPLEMENTED_YET);
    ERRID2STR_HELPER(ERR_ASSERT);
#undef ERRID2STR_HELPER
  default:
    return "invalid error id";
  }
}